all:
  hosts:
    client1: 
      ansible_host: 192.168.99.11
      ansible_user: vagrant 
      ansible_password: vagrant 
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    client2: 
      ansible_host: 192.168.99.12
      ansible_user: vagrant 
      ansible_password: vagrant 
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'