all:
  vars:
    ansible_connection: local
    ansible_user: vagrant
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    client1:
       ansible_host: 192.168.99.11 # A remplacer par l'IP de votre machine cible
       ansible_port: 2222
  vars:
    env: production
    ansible_password: vagrant
